package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/glimpzio/backend/auth"
	"github.com/glimpzio/backend/graph/model"
	"github.com/glimpzio/backend/profile"
)

// UpsertUser is the resolver for the upsertUser field.
func (r *mutationResolver) UpsertUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	middleware := auth.GetMiddleware(ctx)
	if middleware.Token == nil {
		r.Logger.ErrorLog.Println(auth.ErrMissingAuthHeader)

		return nil, auth.ErrMissingAuthHeader
	}

	user, err := r.ProfileService.UpsertUser(middleware.Token.AuthId, &profile.NewUser{
		FirstName:      input.FirstName,
		LastName:       input.LastName,
		PersonalEmail:  input.Email,
		Bio:            input.Bio,
		ProfilePicture: input.ProfilePicture,
		Profile: &profile.Profile{
			Email:    input.Profile.Email,
			Phone:    input.Profile.Phone,
			Website:  input.Profile.Website,
			Linkedin: input.Profile.Linkedin,
		},
	})
	if err != nil {
		r.Logger.ErrorLog.Println(err)

		return nil, err
	}

	r.Logger.InfoLog.Println("upserted user " + user.Id)

	return &model.User{
		ID:             user.Id,
		FirstName:      user.FirstName,
		LastName:       user.LastName,
		Email:          user.Email,
		Bio:            user.Bio,
		ProfilePicture: user.ProfilePicture,
		Profile: &model.Profile{
			Email:    user.Profile.Email,
			Phone:    user.Profile.Phone,
			Website:  user.Profile.Website,
			Linkedin: user.Profile.Linkedin,
		},
	}, nil
}

// CreateInvite is the resolver for the createInvite field.
func (r *mutationResolver) CreateInvite(ctx context.Context) (*model.Invite, error) {
	middleware := auth.GetMiddleware(ctx)
	if middleware.Token == nil {
		r.Logger.ErrorLog.Println(auth.ErrMissingAuthHeader)

		return nil, auth.ErrMissingAuthHeader
	}

	user, err := r.ProfileService.GetUserByAuthId(middleware.Token.AuthId)
	if err != nil {
		r.Logger.ErrorLog.Println(err)

		return nil, err
	}

	r.Logger.InfoLog.Println("retrieved data for user " + user.Id)

	invite, err := r.ProfileService.CreateInvite(user.Id)
	if err != nil {
		r.Logger.ErrorLog.Println(err)

		return nil, err
	}

	r.Logger.InfoLog.Println("created invite " + invite.Id)

	return &model.Invite{
		ID:        invite.Id,
		UserID:    invite.UserId,
		ExpiresAt: int(invite.ExpiresAt.Unix()),
		PublicProfile: &model.PublicProfile{
			FirstName:      user.FirstName,
			LastName:       user.LastName,
			Bio:            user.Bio,
			ProfilePicture: user.ProfilePicture,
			Profile: &model.Profile{
				Email:    user.Profile.Email,
				Phone:    user.Profile.Phone,
				Website:  user.Profile.Website,
				Linkedin: user.Profile.Linkedin,
			},
		},
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	middleware := auth.GetMiddleware(ctx)
	if middleware.Token == nil {
		r.Logger.ErrorLog.Println(auth.ErrMissingAuthHeader)

		return nil, auth.ErrMissingAuthHeader
	}

	user, err := r.ProfileService.GetUserByAuthId(middleware.Token.AuthId)
	if err != nil {
		r.Logger.ErrorLog.Println(err)

		return nil, err
	}

	r.Logger.InfoLog.Println("retrieved data for user " + user.Id)

	return &model.User{
		ID:             user.Id,
		FirstName:      user.FirstName,
		LastName:       user.LastName,
		Email:          user.Email,
		Bio:            user.Bio,
		ProfilePicture: user.ProfilePicture,
		Profile: &model.Profile{
			Email:    user.Profile.Email,
			Phone:    user.Profile.Phone,
			Website:  user.Profile.Website,
			Linkedin: user.Profile.Linkedin,
		},
	}, nil
}

// Invite is the resolver for the invite field.
func (r *queryResolver) Invite(ctx context.Context, id string) (*model.Invite, error) {
	invite, user, err := r.ProfileService.GetInvite(id)
	if err != nil {
		r.Logger.ErrorLog.Println(err)

		return nil, err
	}

	r.Logger.InfoLog.Println("retrieved invite " + invite.Id)

	return &model.Invite{
		ID:        invite.Id,
		UserID:    invite.UserId,
		ExpiresAt: int(invite.ExpiresAt.Unix()),
		PublicProfile: &model.PublicProfile{
			FirstName:      user.FirstName,
			LastName:       user.LastName,
			Bio:            user.Bio,
			ProfilePicture: user.ProfilePicture,
			Profile: &model.Profile{
				Email:    user.Profile.Email,
				Phone:    user.Profile.Phone,
				Website:  user.Profile.Website,
				Linkedin: user.Profile.Linkedin,
			},
		},
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
