// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CustomConnection struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	ConnectedAt int     `json:"connectedAt"`
	FirstName   *string `json:"firstName,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Notes       *string `json:"notes,omitempty"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Website     *string `json:"website,omitempty"`
	Linkedin    *string `json:"linkedin,omitempty"`
}

type Invite struct {
	ID            string         `json:"id"`
	UserID        string         `json:"userId"`
	ExpiresAt     int            `json:"expiresAt"`
	PublicProfile *PublicProfile `json:"publicProfile"`
}

type NewCustomConnection struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Notes     *string `json:"notes,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Website   *string `json:"website,omitempty"`
	Linkedin  *string `json:"linkedin,omitempty"`
}

type NewProfile struct {
	Email    *string `json:"email,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Website  *string `json:"website,omitempty"`
	Linkedin *string `json:"linkedin,omitempty"`
}

type NewUser struct {
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	Email          string      `json:"email"`
	Bio            string      `json:"bio"`
	ProfilePicture *string     `json:"profilePicture,omitempty"`
	Profile        *NewProfile `json:"profile"`
}

type Profile struct {
	Email    *string `json:"email,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Website  *string `json:"website,omitempty"`
	Linkedin *string `json:"linkedin,omitempty"`
}

type PublicProfile struct {
	FirstName      string   `json:"firstName"`
	LastName       string   `json:"lastName"`
	Bio            string   `json:"bio"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Profile        *Profile `json:"profile"`
}

type User struct {
	ID             string   `json:"id"`
	FirstName      string   `json:"firstName"`
	LastName       string   `json:"lastName"`
	Email          string   `json:"email"`
	Bio            string   `json:"bio"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Profile        *Profile `json:"profile"`
}
