version: "3.3"

services:
    db:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test123
        volumes:
            - ../data:/var/data
